#!/usr/bin/env bash
set -euo pipefail

ABI="${1:-x86_64}"
MINSDK="${MINSDK:-26}"
ASR_SDK_ANDROID_REDUCED_ONNX="${ASR_SDK_ANDROID_REDUCED_ONNX:-ON}"
ASR_SDK_ENABLE_FLASHLIGHT_DECODER="${ASR_SDK_ENABLE_FLASHLIGHT_DECODER:-ON}"
ASR_SDK_ENABLE_LEGACY_WFST="${ASR_SDK_ENABLE_LEGACY_WFST:-OFF}"

: "${ANDROID_HOME:?ANDROID_HOME is required}"
: "${ANDROID_NDK:?ANDROID_NDK is required}"
: "${WENET_ROOT:?WENET_ROOT is required}"
: "${ORT_ANDROID_ROOT:?ORT_ANDROID_ROOT is required}"

SDK_ROOT="${SDK_ROOT:-${WENET_ROOT}/SDK/0.0.5_android}"
OUTPUT_DIR="${OUTPUT_DIR:-${SDK_ROOT}/out-sdk-android-${ABI}}"
WENET_BUILD_DIR="${WENET_BUILD_DIR:-${WENET_ROOT}/runtime/onnxruntime/out-android-${ABI}}"

cmake -S "${SDK_ROOT}" -B "${OUTPUT_DIR}" \
  -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK}/build/cmake/android.toolchain.cmake" \
  -DANDROID_ABI="${ABI}" \
  -DANDROID_PLATFORM="android-${MINSDK}" \
  -DANDROID_STL=c++_shared \
  -DCMAKE_BUILD_TYPE=Release \
  -DASR_SDK_WENET_ROOT="${WENET_ROOT}" \
  -DASR_SDK_WENET_BUILD_DIR="${WENET_BUILD_DIR}" \
  -DASR_SDK_ONNXRUNTIME_ROOT="${ORT_ANDROID_ROOT}" \
  -DASR_SDK_BUILD_TOOLS=OFF \
  -DASR_SDK_BUILD_EXAMPLES=OFF \
  -DASR_SDK_BUILD_TESTS=OFF \
  -DASR_SDK_ANDROID_REDUCED_ONNX="${ASR_SDK_ANDROID_REDUCED_ONNX}" \
  -DASR_SDK_ENABLE_FLASHLIGHT_DECODER="${ASR_SDK_ENABLE_FLASHLIGHT_DECODER}" \
  -DASR_SDK_ENABLE_LEGACY_WFST="${ASR_SDK_ENABLE_LEGACY_WFST}"

cmake --build "${OUTPUT_DIR}" -j"$(nproc)"

test -f "${OUTPUT_DIR}/libasr_sdk.so"
file "${OUTPUT_DIR}/libasr_sdk.so" || true
