#!/usr/bin/env python3
"""Print the locale-independent casefold table used by the C++ word speller.

Regenerate with Python's Unicode 13.0.0 database, matching the lexicon builder.
The output is checked into src/flashlight_decoder/unicode_casefold.inc.
"""
import unicodedata

assert unicodedata.unidata_version == "13.0.0", unicodedata.unidata_version
print("// Generated by test/generate_unicode_casefold.py; Unicode 13.0.0.")
print("// Each entry maps one Unicode scalar to its full default casefold.")
for code in range(0x110000):
    value = chr(code)
    folded = value.casefold()
    if value != folded:
        escaped = "".join(f"\\x{byte:02x}" for byte in folded.encode("utf-8"))
        print(f'{{0x{code:X}, "{escaped}"}},')
